---
title: "Results"
author: "Shinichi Nakagawa"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
  #word_document: 
    #reference_docx: "Methods Outline.docx"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)

# clearning up
rm(list=ls())

# loading packages required
pacman::p_load(tidyverse)

# results data
load("../R/results.RData")  
load("../R/results2.RData")  

```

## What to test

###1. Parasitism vs. mutualism (testing Fohrenholz's rule)
Note: i.e. the main test of Fahrenholz’s rule, plus an extension for mutualism, over broad and fine host taxonomy, and broad and fine symbiont taxonomy

Note2: Should we report our result in correlation coefficient *r* or Fisher's *Zr*?; correlation is familiar with people and interpretation may be easier. For example, "*r* = 1" represents perfect congruence (a perfect match between host and symbiont trees) whereas "*r* = -1" represents complete incoherence (complete mismatch - although I do not really know what *r* = -1 (*p* value = 1) really means.; something to discuss and think about it).

  + Main: Overall, our meta-analytic results supported Fahrenholz's rule, host-symbiont tree pairs showed co-divergence more than random (that is, *Zr*~[overall mean]~ $\neq$ 0; multilevel meta-analysis or MMA: *Zr*~[overall mean]~ = `r  dataset$est0[[3]]$estimate %>% round(3)`, 95% confidence interval, CI = [`r  dataset$est0[[3]]$lowerCL %>% round(3)`,`r  dataset$est0[[3]]$upperCL %>% round(3)`]). Notably, the total heterogeneity was moderate (*I*^2^ = `r dataset$est0_I2[[3]][1] %>%  round(4) %>% as.numeric*100`); here the heterogeneity can be considered as variation in effect sizes among different symbiont. Actually, for this kind of meat-analysis, the heterogeneity can be considered to be quite low (as we usually get over 90% heterogeneity or *I*^2^)
  
  <!--- TODO - talk about heterogeneity.....--->
 
  + Parasitism vs. mutualism: Notably, the host-mutualist relationship are more congruent than the host-parasite relationship (*Zr*~[contrast]~ = `r dataset$fit1[[3]]$b[2,1] %>% as.numeric %>% round(3)`, 95% CI = [`r  dataset$fit1[[3]]$ci.lb[2] %>% round(3)`,`r  dataset$fit1[[3]]$ci.ub[2] %>% round(3)`]). 
  
<!--- TODO - need to make a function to extract contrasts --->
<!--- TODO - actually, we may need to rerun the main model without the observational level --->
 
  + Broad host taxonomy: In all board categories (i.e. vertebrates, plants, microbes & invertebrates), microbes as hosts seem to have the most congruent trees among these 4 categories (*Zr*~[vertebrates]~ = `r dataset$est3.1[[3]]$estimate[4] %>% round(3)`, *Zr*~[plants]~ = `r dataset$est3.1[[3]]$estimate[3] %>% round(3)`, *Zr*~[microbes]~ = `r dataset$est3.1[[3]]$estimate[2] %>% round(3)`,*Zr*~[invertebrates]~ = `r dataset$est3.1[[3]]$estimate[1] %>% round(3)`) (note that we will not do fine taxonomy as they are too many and some categories have too few entries to be meaningful)
  
  + Broad symbiont taxonomy: As hosts, plants seem to have the highest congruence although the sample size is limited (*n* = 3; the results should be added later) (note that we will not do fine taxonomy as they are too many and some categories have too few entries to be meaningful)

<!--- TODO - Proccessing file needs to be updated to include Board symbiont  --->

###2. Specialism vs generalism

####2.a Using number of individual links 
Note: i.e. specialists (i.e. cases where `host_range_link_ratio` = 1) vs generalists (i.e. cases where `host_range_link_ratio` > 1)

  + Using 'host range link ratio' (an index of generalism) we found little evidence for generalist symbionts are associated with less congruent host-symbiont relationships (*Zr*~[slop]~ = `r  dataset$est5.1[[3]]$estimate[2]  %>% round(3)`; 95% CI = [`r  dataset$est5.1[[3]]$lowerCL[2]  %>% round(3)`,`r  dataset$est5.1[[3]]$upperCL[2]  %>% round(3)`]). 

####2.b Using an estimate of taxonomic breadth 
Note: specialists (i.e. cases where `host_range_taxonomic_breadth` = 1) vs generalists (cases where `host_range_taxonomic_breadth` > 1)

  + Also, using 'host range taxonomic breath' (another index of generalism) we found little evidence for generalist symbionts are assocaited with less congruent host-symbiont relationships (*Zr*~[slop]~ = `r  dataset$est6.1[[3]]$estimate[2]  %>% round(3)`; 95% CI = [`r  dataset$est6.1[[3]]$lowerCL[2]  %>% round(3)`,`r  dataset$est6.1[[3]]$upperCL[2]  %>% round(3)`]). 

###3. Mode of transmission

####3(a) Broad (vertical transmission vs horizontal transmission plus both)
  
 + As we expected, we found strongest congruence in relationships resulting from vertical transmission followed by mixed modes of transmission (i.e. both vertical and horizontal) and horizontal transmission (*Zr*~[vertical]~ = `r  dataset$est7.1[[3]]$estimate[3]  %>% round(3)`; 95% CI = [`r  dataset$est7.1[[3]]$lowerCL[3]  %>% round(3)`,`r  dataset$est7.1[[3]]$upperCL[3]  %>% round(3)`]; *Zr*~[horizontal]~ = `r  dataset$est7.1[[3]]$estimate[2]  %>% round(3)`; 95% CI = [`r  dataset$est7.1[[3]]$lowerCL[2]  %>% round(3)`,`r  dataset$est7.1[[3]]$upperCL[2]  %>% round(3)`]; *Zr*~[mixed]~ = `r  dataset$est7.1[[3]]$estimate[1]  %>% round(3)`; 95% CI = [`r  dataset$est7.1[[3]]$lowerCL[1]  %>% round(3)`,`r  dataset$est7.1[[3]]$upperCL[1]  %>% round(3)`]).  
 
 + Vertical transmission are associated with a significant increase in congruence compared to horizontal transmission and also both modes (*Zr*~[contrast: vertical vs. mixed]~ = `r dataset$fit7[[3]]$b[3] %>% round(3)`, 95% CI = [`r  dataset$fit7[[3]]$ci.lb[3] %>% round(3)`,`r  dataset$fit7[[3]]$ci.ub[3] %>% round(3)`]; I need to get stats for "vertical vs. horizontal")
 
 + Importantly, the mode of transmission underlies why host-mutualist relationships are more congruent than host-parasite relationships (35 out of 65 in mutualists while 0 out of 133 in parasites).
 
<!--- TODO - Probably this is where we need to do SEM or Path analysis to show the casual relationship between the model of transmission and congruence  --->
 
<!--- TODO - We probably need to do some sort of model selection and model averaging procedure!; the model with types of symbiosis and model of transmission - where parasite vs. mutualist becomes non-sig  --->

####3(b) Fine (various:  autonomous, bodily fluid, contact environmental, trophic, vector, vertical) 

 + (Note): this categorization may not be useful - potentially we have this in Suppl but currently, this is ignored

###4. Endosymbiosis vs ectosymbiosis (plus both)

 + Rather surprisingly, endo- or ectosybiosis does not seem to affect tree congruence (*Zr*~[endosymbiosis]~ = `r  dataset$est9.1[[3]]$estimate[2]  %>% round(3)`; 95% CI = [`r  dataset$est9.1[[3]]$lowerCL[2]  %>% round(3)`,`r  dataset$est9.1[[3]]$upperCL[2]  %>% round(3)`]; *Zr*~[ectosymbiosis]~ = `r  dataset$est9.1[[3]]$estimate[1]  %>% round(3)`; 95% CI = [`r  dataset$est9.1[[3]]$lowerCL[1]  %>% round(3)`,`r  dataset$est9.1[[3]]$upperCL[1]  %>% round(3)`]; *Zr*~[mixed]~ = `r  dataset$est9.1[[3]]$estimate[3]  %>% round(3)`; 95% CI = [`r  dataset$est9.1[[3]]$lowerCL[3]  %>% round(3)`,`r  dataset$est9.1[[3]]$upperCL[3]  %>% round(3)`]). 

###5. Whether symbiont is eukaryotes or prokayotes

 + Also, it did not have much influence on tree congruence whether symbionts are eukaryotes or prokayotes (*Zr*~[eukaryotes]~ = `r  dataset$est10.1[[3]]$estimate[2]  %>% round(3)`; 95% CI = [`r  dataset$est10.1[[3]]$lowerCL[2]  %>% round(3)`,`r  dataset$est10.1[[3]]$upperCL[2]  %>% round(3)`]; *Zr*~[prokayotes]~ = `r  dataset$est10.1[[3]]$estimate[1]  %>% round(3)`; 95% CI = [`r  dataset$est10.1[[3]]$lowerCL[1]  %>% round(3)`,`r  dataset$est10.1[[3]]$upperCL[1]  %>% round(3)`])
  
###Caveats

Our results are bounded at the number of randomization conducted (I will elaborate on this more later). Therefore, our congruence is likely to be underestimate although it does not seem like that this bounding problem is biasing our results in particular categories (i.e. mutualists vs. parasites).


<!--- --->